# Generated by Django 3.1.3 on 2020-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数'),
        ),
    ]
